### ISSUE TITLE
Google Images

### ISSUE THREAD

**Issue by ptahchiev** [jirkapinkas/jsitemapgenerator#1]
Hi there,

I like your project - it's awesome :) Can you please add support for google images inside the sitemap, like here:

https://support.google.com/webmasters/answer/178636?hl=en

Just need to extend WebPage and create a new object GoogleWebPage that has the additional attributes.

Thank you :)

**Comment by tsachev** [comment]
Hi it would be nice to have this feature.
If you do not want to support google specific task at least provide a hook (like protected method called in `contructUrl()# where users can add custom tags inside `<url>`

**Comment by jirkapinkas** [comment]
Done. Just released 2.0 version. Note that 2.0 version is not fully backwards compatible, but the changes are for the best.
