### ISSUE TITLE
Images are added to existing sitemap incorrectly

### ISSUE THREAD

**Issue by julieromm** [jirkapinkas/jsitemapgenerator#3]
Hi,

It looks like image tags are being added to an existing sitemap incorrectly.  Specifically, images pertaining to a specific page should be listed inside the url element, as described here:
https://support.google.com/webmasters/answer/178636?hl=en

While your code produces the following XML:

```
<loc>http://www.somedomain.com/url/path</loc>
<lastmod>2015-11-25T09:19-05:00</lastmod>
<changefreq>daily</changefreq>
<priority>0.5</priority>
</url>
<image:image>
<image:loc>imageUrl1</image:loc>
</image:image>
<image:image>
<image:loc>imageUrl2</image:loc>
</image:image>
<url>
...
```

The problematic methods are constructSitemap and constructUrl inside cz.jiripinkas.jsitemapgenerator.generator.SitemapGenerator class. 
The simplest way to fix would be to move out.append("</url>\n"); statement from constructUrl method and into constructSitemap, line 52 (i.e. after images elements have been constructed).

Alternatively, constructImage should be called from inside constructUrl(WebPage webPage), before writing out the closing </url> tag.
 
Very useful project otherwise!

Thanks.

**Comment by julieromm** [comment]
Sorry, accidentally created a copy...

**Comment by jirkapinkas** [comment]
No problem :-) I just pushed (hopefully fixed) version and in a few hours new version (2.2) will be synced to Maven Central.

**Comment by julieromm** [comment]
AWESOME!!!  Thank you so much! [&#X1f60a]   Looks good.

Thanks again for a quick turnaround.

Julie

________________________________
